version: '3.8'
services:
  db:
    container_name: "db"
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petsdb
    command: -p 8787
    expose:
      - 8787
    ports:
      - 9000:8787
    # volumes:
    #   - db-data:/var/lib/postgresql/data

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     env_file:
#       - .env
#     container_name: task_api
#     command: ./app.sh
#     ports:
#       - 7050:8000
#     depends_on:
#       - db
# volumes:
#   db-data: