# Generated by Django 4.2.6 on 2023-11-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField()),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('accounting_unit', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=40)),
                ('manufacturer', models.CharField()),
                ('article_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockOrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.productbd')),
                ('stock_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.stockorderdb')),
            ],
        ),
        migrations.AddField(
            model_name='stockorderdb',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.userbd'),
        ),
        migrations.CreateModel(
            name='SellPriceBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField()),
                ('price', models.FloatField()),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.discountbd')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.productbd')),
            ],
        ),
        migrations.CreateModel(
            name='OrderitemDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockitem_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.orderbd')),
                ('sell_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.sellpricebd')),
            ],
        ),
        migrations.AddField(
            model_name='orderbd',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.userbd'),
        ),
    ]
