# Generated by Django 4.2.7 on 2023-11-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("accounting_unit", models.CharField(max_length=20)),
                ("product_category", models.CharField(max_length=40)),
                ("manufacturer", models.CharField(max_length=255)),
                ("article_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StockOrderBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StockOrderItemBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("purchase_price", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.productbd"
                    ),
                ),
                (
                    "stock_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockitem_list",
                        to="pet.stockorderbd",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stockorderbd",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pet.userbd"
            ),
        ),
        migrations.CreateModel(
            name="SellPriceBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateTimeField()),
                ("date_stop", models.DateTimeField()),
                ("price", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.productbd"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderitemBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("sell_price", models.PositiveIntegerField()),
                ("discount", models.PositiveIntegerField()),
                ("total", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_list",
                        to="pet.orderbd",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.productbd"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderbd",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pet.userbd"
            ),
        ),
        migrations.CreateModel(
            name="DiscountBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateTimeField()),
                ("date_stop", models.DateTimeField()),
                ("discount", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.productbd"
                    ),
                ),
            ],
        ),
    ]
