# Generated by Django 4.2.7 on 2023-11-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitembd",
            name="discount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
