# Generated by Django 4.2.6 on 2023-11-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_sellpricebd_discount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpricebd',
            name='discount_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.discountbd'),
        ),
    ]
